import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { RiPlayList2Line, RiPlayFill, RiDeleteBinLine } from 'react-icons/ri';
import { usePlayerStore } from '../stores/playerStore';
export default function QueuePage() {
    const { queue, queueIndex, currentTrack, playTrack, removeFromQueue, clearQueue } = usePlayerStore();
    return (_jsxs("div", { className: "page-enter space-y-4 sm:space-y-6 pb-8", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-10 w-10 sm:h-12 sm:w-12 items-center justify-center rounded-lg sm:rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500", children: _jsx(RiPlayList2Line, { size: 20, className: "text-white" }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-xl sm:text-3xl font-bold", children: "Queue" }), _jsxs("p", { className: "text-xs sm:text-sm text-softText", children: [queue.length, " tracks in queue"] })] })] }), queue.length > 0 && (_jsxs("button", { onClick: clearQueue, className: "flex items-center gap-1.5 sm:gap-2 rounded-full bg-white/10 px-3 py-1.5 sm:px-4 sm:py-2 text-xs sm:text-sm font-semibold text-white transition hover:bg-white/20", children: [_jsx(RiDeleteBinLine, { size: 16 }), "Clear Queue"] }))] }), currentTrack && (_jsxs("div", { className: "rounded-xl border border-accent/30 bg-accent/10 p-4", children: [_jsx("div", { className: "mb-2 text-xs font-bold uppercase tracking-wider text-accent", children: "Now Playing" }), _jsxs("div", { className: "flex items-center gap-4", children: [currentTrack.coverUrl ? (_jsx("img", { src: currentTrack.coverUrl, alt: currentTrack.title, className: "h-12 w-12 sm:h-16 sm:w-16 flex-shrink-0 rounded-lg object-cover" })) : (_jsx("div", { className: "h-12 w-12 sm:h-16 sm:w-16 flex-shrink-0 rounded-lg", style: { background: `linear-gradient(135deg, ${currentTrack.coverGradient?.[0] || '#333'}, ${currentTrack.coverGradient?.[1] || '#222'})` } })), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("div", { className: "truncate text-base sm:text-lg font-bold text-white", children: currentTrack.title }), _jsx("div", { className: "truncate text-xs sm:text-sm text-softText", children: currentTrack.artist })] })] })] })), queue.length > 0 ? (_jsxs("div", { children: [_jsx("h2", { className: "mb-3 text-sm font-bold uppercase tracking-wider text-softText", children: "Up Next" }), _jsx("div", { className: "space-y-2", children: queue.map((track, index) => {
                            const isCurrentTrack = index === queueIndex;
                            if (isCurrentTrack)
                                return null; // Skip current track as it's shown above
                            return (_jsxs("div", { className: "group flex w-full items-center gap-3 sm:gap-4 rounded-xl bg-glass-card backdrop-blur-xl p-2.5 sm:p-3 transition hover:bg-card-hover", children: [_jsx("span", { className: "w-8 text-center text-sm font-bold text-dimText", children: index + 1 }), track.coverUrl ? (_jsx("img", { src: track.coverUrl, alt: track.title, className: "h-11 w-11 sm:h-14 sm:w-14 flex-shrink-0 rounded-lg object-cover" })) : (_jsx("div", { className: "h-11 w-11 sm:h-14 sm:w-14 flex-shrink-0 rounded-lg", style: { background: `linear-gradient(135deg, ${track.coverGradient?.[0] || '#333'}, ${track.coverGradient?.[1] || '#222'})` } })), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("div", { className: "truncate text-sm sm:text-base font-bold text-white", children: track.title }), _jsx("div", { className: "truncate text-xs sm:text-sm text-softText", children: track.artist })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: () => playTrack(track, queue), className: "hidden h-10 w-10 items-center justify-center rounded-full bg-accent text-white shadow-glow-sm transition hover:scale-110 group-hover:flex", children: _jsx(RiPlayFill, { size: 18, className: "ml-0.5" }) }), _jsx("button", { onClick: () => removeFromQueue(index), className: "hidden h-10 w-10 items-center justify-center rounded-full bg-white/10 text-white transition hover:bg-red-500/20 hover:text-red-400 group-hover:flex", children: _jsx(RiDeleteBinLine, { size: 16 }) })] })] }, `${track.id}-${index}`));
                        }) })] })) : (_jsxs("div", { className: "flex flex-col items-center justify-center rounded-2xl border-2 border-dashed border-white/5 py-16", children: [_jsx(RiPlayList2Line, { size: 48, className: "mb-4 text-dimText" }), _jsx("p", { className: "text-lg font-bold text-white", children: "Queue is empty" }), _jsx("p", { className: "text-sm text-dimText", children: "Add tracks to your queue to see them here" })] }))] }));
}
