import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from 'react';
import { RiTimeLine, RiPlayFill } from 'react-icons/ri';
import { useLocalLibraryStore } from '../stores/localLibraryStore';
import { usePlayerStore } from '../stores/playerStore';
export default function RecentlyPlayedPage() {
    const { getRecentlyPlayed } = useLocalLibraryStore();
    const { playTrack } = usePlayerStore();
    const { localTracks } = useLocalLibraryStore();
    const recentTracks = useMemo(() => getRecentlyPlayed(50), [getRecentlyPlayed]);
    return (_jsxs("div", { className: "page-enter space-y-4 sm:space-y-6 pb-8", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-10 w-10 sm:h-12 sm:w-12 items-center justify-center rounded-lg sm:rounded-xl bg-gradient-to-br from-gradient-from to-accent", children: _jsx(RiTimeLine, { size: 20, className: "text-white" }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-xl sm:text-3xl font-bold", children: "Recently Played" }), _jsx("p", { className: "text-sm text-softText", children: "Your recently played tracks" })] })] }), recentTracks.length > 0 ? (_jsx("div", { className: "space-y-2", children: recentTracks.map((track, index) => (_jsxs("button", { onClick: () => playTrack(track, localTracks), className: "group flex w-full items-center gap-3 sm:gap-4 rounded-xl bg-glass-card backdrop-blur-xl p-2.5 sm:p-3 text-left transition hover:bg-card-hover", children: [track.coverUrl ? (_jsx("img", { src: track.coverUrl, alt: track.title, className: "h-11 w-11 sm:h-14 sm:w-14 flex-shrink-0 rounded-lg object-cover" })) : (_jsx("div", { className: "h-11 w-11 sm:h-14 sm:w-14 flex-shrink-0 rounded-lg", style: { background: `linear-gradient(135deg, ${track.coverGradient?.[0] || '#333'}, ${track.coverGradient?.[1] || '#222'})` } })), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("div", { className: "truncate text-sm sm:text-base font-bold text-white", children: track.title }), _jsx("div", { className: "truncate text-xs sm:text-sm text-softText", children: track.artist })] }), _jsx("div", { className: "hidden h-10 w-10 items-center justify-center rounded-full bg-accent text-white shadow-glow-sm group-hover:flex", children: _jsx(RiPlayFill, { size: 18, className: "ml-0.5" }) })] }, `${track.id}-${index}`))) })) : (_jsxs("div", { className: "flex flex-col items-center justify-center rounded-2xl border-2 border-dashed border-white/5 py-16", children: [_jsx(RiTimeLine, { size: 48, className: "mb-4 text-dimText" }), _jsx("p", { className: "text-lg font-bold text-white", children: "No recently played tracks" }), _jsx("p", { className: "text-sm text-dimText", children: "Start playing music to see your history here" })] }))] }));
}
